praw-dev/prawcore

- examples/device_id_auth_trophies.py
- prawcore/__init__.py
- prawcore/auth.py
- tests/test_authorizer.py
This feature provides [application-only OAuth2 flow](https://github.com/reddit/reddit/wiki/OAuth2/601b10dc29d443c2b6c0d652bb71e972618117a3) support for 'installed' applicaitons.
All tests passed in my environment with follwoing command:
$ PRAW_CLIENT_ID=$INSTALLED_CLIENT_ID PRAW_CLIENT_SECRET='' ./pre_push.sh
but output cassetts get garbled with `<CLIENT_SECRET>` place holders.
> Add DeviceIDAuthorizer to support app-only OAuth2 for 'install' apps

- AUTHORS.rst
- CHANGES.rst
- examples/caching_requestor.py
- prawcore/requestor.py
- tests/test_requestor.py
I'm using cachecontrol with PRAW and being able to pass a custom Session would eliminate the need to subclass Requestor just to wrap/tinker with the session.
> Allow passing custom Session class to Requestor

- examples/caching_requestor.py
- prawcore/exceptions.py
- prawcore/sessions.py
- tests/cassettes/Session_request__conflict.json
- tests/test_sessions.py
This just adds a new ResponseException that's raised on a [409 HTTP response](https://httpstatuses.com/409). On Reddit, this can happen when updating a wiki page with the `previous` parameter set to an outdated revision, i.e. because multiple clients try to make edits simultaneously. Adding this exception means that PRAW clients can handle concurrent wiki edits without having to re-fetch the page.
> Raise Conflict on 409 HTTP response

- AUTHORS.rst
- CHANGES.rst
- prawcore/exceptions.py
- prawcore/sessions.py
- tests/cassettes/Session_request__unsupported_media_type.json
- tests/test_sessions.py
Fixes #65.
This adds class `SpecialError`. When raised, it uses the `message` field from the response in the text of the exception. `message`, `reason`, and `special_errors` are all saved on the `SpecialError` object.
> Add SpecialError to handle HTTP 415.

- CHANGES.rst
- prawcore/const.py
- prawcore/rate_limit.py
There's some discussion about this issue here: https://www.reddit.com/r/redditdev/comments/ajmy2t/praw_long_sleep/eezw2ke/
> Don't allow RateLimiter to wait longer than next request timestamp

- setup.py
mock is unpinned in praw:setup.py:tests_require ("mock >=0.8",)
Unpin it here to match, allowing mock 3.x to satisfy the dependency.
Testing with latest upstream sources allows us to pick up incompatibilities sooner and reduces friction for downstream packages who generally use system provided packages (including tests_requires) to QA, and who's clean-room QA systems generally don't allow network connectivity during builds/QA/packaging, which precludes fetching dependencies from remote sources.
Tests for prawcore 1.0.1 sdist pass with mock 3.0.4 (latest at the time of writing)
Ran 90 tests in 1.662s OK
> Unpin mock dependency

- AUTHORS.rst
- CHANGES.rst
- prawcore/rate_limit.py
- tests/test_rate_limit.py
Closes #89 
Unit tests for this was tricky, since the new formula dynamically calculates the correct delay over several requests, rather than just the first one. But I updated the tests as best I could.
> Rate limit

- CHANGES.rst
- prawcore/sessions.py
- tests/cassettes/Session_request__patch.json
We send this key-value pair in all bodies (such as in POST requests). We should do the same when the `json` parameter contains a `dict`.
This PR lays the groundwork for allowing PRAW to properly make JSON requests.
Had to re-record a PATCH test because that was the only test that
already used the json parameter, and this changed that behavior.
> Set `api_type=json` when requesting with a JSON dict.

- AUTHORS.rst
I accidentally used `?` instead of `>`.
> Fix minor typo in AUTHORS.rst

- setup.py
no longer compatible with python2's urllib
```
...
prawcore/exceptions.py:2: in <module>
from urllib.parse import urlparse
E   ImportError: No module named parse
builder for '/nix/store/3l1rqygq58hbwyzn6fqx8x4djbmzgggh-python2.7-prawcore-1.4.0.drv' failed with exit code 4
```
> Fail on attempting to install on python2

- setup.py
> Require python 3.6 properly

- .github/workflows/ci.yml
- AUTHORS.rst
- CHANGES.rst
- README.rst
- examples/caching_requestor.py
- examples/device_id_auth_trophies.py
- examples/obtain_refresh_token.py
- examples/read_only_auth_trophies.py
- examples/script_auth_friend_list.py
- prawcore/__init__.py
- prawcore/auth.py
- prawcore/exceptions.py
- prawcore/rate_limit.py
- prawcore/requestor.py
- prawcore/sessions.py
- prawcore/util.py
- pre_push.sh
- setup.py
- tests/__init__.py
- tests/conftest.py
- tests/test_authenticator.py
- tests/test_authorizer.py
- tests/test_rate_limit.py
- tests/test_requestor.py
- tests/test_sessions.py
This PR does the following:
- Makes flake8 ignore `.eggs` and `.venv` directories
- Fixes spelling mistakes
- Converts `.format()` to f-string literal and adds `flynt` for enforcement
- Sorts imports with `isort`
- Formats code to 88 characters with black (one pass with --experimental-string-processing to normalize strings and a second pass without it)
- Cleans up docs:
- Format docs to 88 characters where possible
- Format all code snippets with black
- Indent all blocks to 4 spaces
- Change `*` bullets to `-`
> Reformat to 88 and code/documentation cleanup

- pre_push.sh
I guess `function foo ()` is bash syntax, so if you do `./pre_push.sh` then the `#!/bin/sh` shebang means that the script doesn't actually work.
> Use sh syntax for pre_push.sh function

- prawcore/auth.py
Per RFC6749, this parameter must be in the ASCII range 0x20-0x7E.[^1]
Empirically, Reddit's response will not be usable if this rule is not
followed.
[1]: https://tools.ietf.org/html/rfc6749#appendix-A.5
> Add note about valid authorize_url.state param

- CHANGES.rst
- prawcore/auth.py
- tests/cassettes/ScriptAuthorizer_refresh_with__invalid_otp.json
- tests/cassettes/ScriptAuthorizer_refresh_with__valid_otp.json
- tests/conftest.py
- tests/test_authorizer.py
- tests/test_sessions.py
This feature allows script authorizations to supply an optional 'otp' parameter when authenticating. This is accomplished by adding a callback named `two_factor_callback` to the method `ScriptAuthorizer.refresh.` See [97](https://github.com/praw-dev/prawcore/pull/97) and praw's [1496](https://github.com/praw-dev/praw/issues/1496) for previous discussions of this. 
---
I have added some support for running other tests with 2fa enabled. There is now a `test_two_factor_callback` function in conftest, which is used in script auth tests to generate an OTP. By default, it returns None, which allows all tests to pass. This PR also adds two tests that show what successful and unsuccessful authorization attempts look like. I have included a third test in test_authorizer, `test_refresh_with__2fa`, …
> Add two factor callback

- CHANGES.rst
- prawcore/exceptions.py
- prawcore/sessions.py
- tests/cassettes/Session_request__too__many_requests__with_retry_headers.json
- tests/cassettes/Session_request__too__many_requests__without_retry_headers.json
- tests/test_sessions.py
This adds a TooManyRequests exception.
In PRAW's [issue 1716](https://github.com/praw-dev/praw/issues/1716), 429s are being returned because Reddit [refuses to serve](https://www.reddit.com/dev/api#GET_api_morechildren) concurrent requests to the morechildren endpoint (see the note in the link), and [returns a 429](https://github.com/reddit-archive/reddit/blob/master/r2/r2/controllers/api.py#L3572) when it does get concurrent requests. I was able to get a 429 error shortly after starting two instances of PRAW that simultaneously ran
for submission in reddit.subreddit(HIGH_TRAFFIC_SUB).top("all"):
submission.comments.replace_more(limit= None)
I checked the ratelimit headers on the tape I made of this test and confirmed that the errors happened even with nearly all 600 requests remaining. …
> Add TooManyRequests Exception

- CHANGES.rst
- prawcore/auth.py
- prawcore/sessions.py
- tests/cassettes/Authorizer_revoke__access_token_with_refresh_set.json
- tests/cassettes/Authorizer_revoke__access_token_without_refresh_set.json
- tests/cassettes/Authorizer_revoke__refresh_token_with_access_set.json
- tests/cassettes/Authorizer_revoke__refresh_token_without_access_set.json
- tests/cassettes/Session_request__accepted.json
- tests/cassettes/TrustedAuthenticator_revoke_token.json
- tests/cassettes/TrustedAuthenticator_revoke_token__with_access_token_hint.json
- tests/cassettes/TrustedAuthenticator_revoke_token__with_refresh_token_hint.json
- tests/cassettes/UntrustedAuthenticator_revoke_token.json
- tests/test_sessions.py
Changes success status for token revocation from 204 to 200.
Reddit changed the status code of the response for token revocation attempts that are made with the correct authorization headers (but not necessarily the right token) from 204 to 200, presumably to be RFC 7009 [compliant](https://datatracker.ietf.org/doc/html/rfc7009/#section-2.2). The only thing from an employee I could find on redditdev about this was [this comment](https://www.reddit.com/r/redditdev/comments/jl232s/help_did_something_change_with_the_authentication/gamoyky/).
This doesn't affect prawcore's ability to revoke a token, but it does create an unfortunate bug. Because prawcore sees a 200 instead of a 204, it throws a response exception before it can clear the token. Fortunately, the next request results in a 401 …
> api/v1/revoke_token HTTP status code change

- CHANGES.rst
- prawcore/sessions.py
- tests/cassettes/Session_request__redirect_301.json
- tests/test_sessions.py
Reddit has a feature called "topics", which have addresses that look like this: `https://www.reddit.com/t/animals_and_pets/` . These pages are inaccessible from the API: attempting to get `https://oauth.reddit.com/t/animals_and_pets/` results in a redirect to `https://oauth.reddit.com/r/t:animals_and_pets/`. Following that latter link results in a 404 (go figure). I added 301s to the list of status exceptions.
This change does not need a test to ensure 100% code coverage, but I added one in case it is wanted.
> Raise Redirect exception on 301 HTTP responses

- CHANGES.rst
- prawcore/requestor.py
- tests/test_requestor.py
Adds a timeout parameter to the Requestor class. Once this is done, the corresponding PRAW change is just adding the line ` self.config.timeout,` to [Reddit. _prepare_prawcore](https://github.com/praw-dev/praw/blob/master/praw/reddit.py#L487), so that it becomes
def _prepare_prawcore(self, requestor_class=None, requestor_kwargs=None):
requestor_class = requestor_class or Requestor
requestor_kwargs = requestor_kwargs or {}
requestor = requestor_class(
USER_AGENT_FORMAT.format(self.config.user_agent),
self.config.oauth_url,
self.config.reddit_url,
self.config.timeout,
**requestor_kwargs,
)
if self.config.client_secret:
self._prepare_trusted_prawcore(requestor)
else:
self._prepare_untrusted_prawcore(requestor)
You could also convert timeout to a …
> Add timeout parameter to Requestor

- .github/workflows/ci.yml
Similar to what was done in https://github.com/praw-dev/praw/pull/1772, the coveralls is no more fixed to the commit. But is open to update now as it is tied to coverallsapp@master
> Bugfix/coveralls GitHub action updated (#1772)

- CHANGES.rst
- prawcore/const.py
Should be the last time. There was a broken version specifier.
> Revert "Release v2.4.0"

- prawcore/__init__.py
- prawcore/const.py
- prawcore/requestor.py
- tools/set_version.py
As discussed in #164 , moving `__version__` from `const.py` to be directly in `__init__,py` allows Flit to statically introspect it, preventing `requests` from being required as an unspecified, implict build-time dependency, causing build/install failures in certain scenarios. I've tested and confirmed locally that this fix allows successfully building and installing `prawcore` without having `requests` in the local environment.
Additionally, I've updated the one internal module using this value from `const.py` to use that from `__init__.py`. I did have to switch from a relative `from` import to an absolute import to avoid an import cycle error; alternatively, I could also move the import to be inside the relevant function, though I figured the former would be more acceptable/less …
> Move version from const.py to __init__.py for Flit static introspection

- CHANGES.rst
- prawcore/auth.py
- prawcore/const.py
- prawcore/rate_limit.py
- prawcore/sessions.py
- tests/unit/test_rate_limit.py
Additionally, replace uses of `time.time` with `time.monotonic` or `time.monotonic_ns`.
> Fix occasional bug with 0 requests remaining and 0 seconds before reset

- CHANGES.rst
- prawcore/rate_limit.py
- tests/unit/test_rate_limit.py
Should fully resolve https://github.com/praw-dev/prawcore/issues/198
> Sleep for a full second when rate limit is expired with no remaining requests
